### ISSUE TITLE
questions in calculate_r_squared?

### ISSUE THREAD

**Issue by jeremykid** [mp2893/doctorai#8]
Hello Dr. Edward Choi

I am reading the code and trying to follow your work. I have questions in calculate_r_squared function.

Should the **mean_duration** in R_2(coefficient of determination) be updated by argument **use_log_time** in testDoctorAI.py?

In my understanding, R_2(coefficient of determination)
![image](https://user-images.githubusercontent.com/10427900/75216506-711e4c80-5751-11ea-8a0f-a0aa0c0c5269.png)

In testDoctorAI.py [calculate_r_squared function ](https://github.com/mp2893/doctorai/blob/master/testDoctorAI.py#L32) , I assume mean_duration is the mean of y in R_2(coefficient of determination). 

In [help](https://github.com/mp2893/doctorai/blob/master/testDoctorAI.py#L265) said mean_duration is the mean value of the durations. 

But when the use_log_time = 1, the mean_duration still uses the number of days instead of log(days).

**Comment by mp2893** [comment]
Hi Jeremykid,

Your observation is true. Thanks for catching the bug!
Since mean_duration is a constant, it should be fine to use the current R^2 implementation for comparing model performance or tuning hyperparams. But we should correct the bug nonetheless, to provide accurate information. Would you like to make a pull request?

Best,
Ed

**Comment by jeremykid** [comment]
Dear Dr. Edward Choi

Thank you for replying me, I created a pull request, could you help to review?

Best wishes
Jeremykid

**Comment by mp2893** [comment]
Awesome. Just approved the pull request. Thanks!
